app:
  auth-server: localhost

server:
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: 10s
  rabbitmq:
    host: 127.0.0.1
    port: 5672
  cloud:
    stream:
      kafka:
        binder:
          brokers: 127.0.0.1
          defaultBrokerPort: 9092
      default-binder: rabbit

# WARNING: Exposing all management endpoints over http should only be used during development,
# must be locked down in production!
management:
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
      group:
        readiness:
          include: "*"
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0
    enabled: true
    propagation:
      type: w3c
  metrics:
    distribution:
      percentiles-histogram:
        greeting: true
        http:
          server:
            requests: true
  # Must be configured like this.
  zipkin.tracing.endpoint: http://zipkin-server:9411/api/v2/spans

---
spring:
  cloud:
    activate:
      on-profile: docker
    stream:
      kafka:
        binder:
          brokers: kafka
  rabbitmq:
    host: rabbitmq


app:
  auth-server: auth-server

---
spring:
  config:
    activate:
      on-profile: production
  rabbitmq:
    host: 172.17.0.1

management:
  endpoints:
    web:
      exposure:
        include: health, info, circuitbreakerevents

---
spring:
  config.activate.on-profile: kafka
  cloud.stream:
    default-binder: kafka
    kafka.binder.replication-factor: 1
  kafka.bootstrap-servers: kafka:9092

management.health.rabbit.enabled: false

