app:
  eureka-username: username
  eureka-password: '{cipher}32cb5f48e9b150ad60ce99555529f4b2187ae026b5b9548414588f6f4a24155c'
  eureka-server: localhost
  auth-server: localhost

eureka:
  client:
    service-url:
      defaultZone: http://${app.eureka-username}:${app.eureka-password}@${app.eureka-server}:8761/eureka/
    initial-instance-info-replication-interval-seconds: 5
    registry-fetch-interval-seconds: 5
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5

spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: '{cipher}28748282115d6dfefcb2cc0ede2b1b608490db0eb58c07492aa6c024ad83d683'
  cloud:
    stream:
      kafka:
        binder:
          brokers: 127.0.0.1
          defaultBrokerPort: 9092
      default-binder: rabbit

# WARNING: Exposing all management endpoints over http should only be used during development,
# must be locked down in production!
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
