app:
  auth-server: localhost

server:
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: 10s
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: '{cipher}28748282115d6dfefcb2cc0ede2b1b608490db0eb58c07492aa6c024ad83d683'
  cloud:
    stream:
      kafka:
        binder:
          brokers: 127.0.0.1
          defaultBrokerPort: 9092
      default-binder: rabbit

# WARNING: Exposing all management endpoints over http should only be used during development,
# must be locked down in production!
management:
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
      group:
        readiness:
          include: "*"
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0
    enabled: true
    propagation:
      type: w3c
  metrics:
    distribution:
      percentiles-histogram:
        greeting: true
        http:
          server:
            requests: true
  # Must be configured like this.
  zipkin.tracing.endpoint: http://zipkin:9411/api/v2/spans
