server:
  port: 9999
  forward-headers-strategy: framework

spring:
  application:
    name: auth-server

logging.level:
  root: info
#  org.springframework.security: trace

---
spring:
  config:
    activate:
      on-profile: docker

server:
  port: 80

---
spring:
  config:
    activate:
      on-profile: production

logging:
  level:
    root: warn
