server:
  port: 8443
  ssl:
    key-store-type: PKCS12
    key-store: classpath:keystore/edge.p12
    key-alias: localhost

spring:
  ## set to true to debug security WebFlux headers.
  codec:
    log-request-details: true
  application.name: gateway
  security.oauth2.resourceserver.jwt.issuer-uri: https://dev-k26mww20c882irv6.us.auth0.com/
  cloud:
    gateway:
      routes:
        - id: product-composite
          uri: http://product-composite
          predicates:
            - Path=/product-composite/**

        - id: oauth2-server
          uri: http://${app.auth-server}
          predicates:
            - Path=/oauth2/**

        - id: oauth2-login
          uri: http://${app.auth-server}
          predicates:
            - Path=/login/**

        - id: oauth2-error
          uri: http://${app.auth-server}
          predicates:
            - Path=/error/**

        - id: product-composite-swagger-ui
          uri: http://product-composite
          predicates:
            - Path=/openapi/**

        - id: product-composite-swagger-ui-webjars
          uri: http://product-composite
          predicates:
            - Path=/webjars/**

logging:
  level:
    root: info
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: info
    org.springframework.cloud.gateway: trace
    org.springframework.web.server.adapter.HttpWebHandlerAdapter: trace
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

management:
    gateway.enabled: true

---
spring:
  config:
    activate:
      on-profile: production

logging:
  level:
    root: WARN
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: WARN
    org.springframework.cloud.gateway: WARN
    org.springframework.web.server.adapter.HttpWebHandlerAdapter: WARN





