server:
  port: 8443
  ssl:
    key-store-type: PKCS12
    key-store: classpath:keystore/edge.p12
    key-store-password: '{cipher}32cb5f48e9b150ad60ce99555529f4b2187ae026b5b9548414588f6f4a24155c'
    key-alias: localhost

spring:
  ## set to true to debug security WebFlux headers.
  codec:
    log-request-details: true
  application.name: gateway
  security.oauth2.resourceserver.jwt.issuer-uri: https://dev-k26mww20c882irv6.us.auth0.com/
  cloud:
    gateway:
      routes:
        - id: product-composite
          uri: http://product-composite
          predicates:
            - Path=/product-composite/**

        - id: oauth2-server
          uri: http://${app.auth-server}
          predicates:
            - Path=/oauth2/**

        - id: oauth2-login
          uri: http://${app.auth-server}
          predicates:
            - Path=/login/**

        - id: oauth2-error
          uri: http://${app.auth-server}
          predicates:
            - Path=/error/**

        - id: product-composite-swagger-ui
          uri: http://product-composite
          predicates:
            - Path=/openapi/**

        - id: product-composite-swagger-ui-webjars
          uri: http://product-composite
          predicates:
            - Path=/webjars/**

        - id: config-server
          uri: http://config-server:8888
          predicates:
            - Path=/config/**
          filters:
            - RewritePath=/config/(?<segment>.*), /$\{segment}


logging:
  level:
    root: info
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: info
    org.springframework.cloud.gateway: trace
    org.springframework.web.server.adapter.HttpWebHandlerAdapter: trace
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

management:
    gateway.enabled: true



