server:
  port: 7001
  error.include-message: always

app:
  eureka-username: username
  eureka-password: password
  eureka-server: localhost

spring:
  application.name: product
  data.mongodb:
      host: localhost
      port: 27017
      database: productdb
  cloud:
    function.definition: messageProcessor
    stream:
      default-binder: rabbit
      default.contentType: application/json
      bindings:
        messageProcessor-in-0:
          destination: products
          group: productsGroup
          consumer:
            max-attempts: 3
            back-off-initial-interval: 500
            back-off-max-interval: 1000
            back-off-multiplier: 2.0

      rabbit.bindings:
        messageProcessor-in-0:
          consumer:
            auto-bind-dlq: true
            republish-to-dlq: true
      kafka:
        bindings:
          messageProcessor-in-0:
            consumer:
              enable-dlq: true
        binder:
          brokers: 127.0.0.1
          defaultBrokerPort: 9092

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://${app.eureka-username}:${app.eureka-password}@${app.eureka-server}:8761/eureka/
    initial-instance-info-replication-interval-seconds: 5
    registry-fetch-interval-seconds: 5
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5


logging:
  level:
    root: info
    org.tbl.microdaddy: debug
    org.springframework.data.mongodb.core.ReactiveMongoTemplate: debug

management:
  endpoint.health.show-details: always
  endpoints.web.exposure.include: "*"


