spring:
  config.activate.on-profile: streaming_partitioned
  cloud.stream.bindings:
    products-out-0:
      producer:
        partition-key-expression: headers['partitionKey']
        partition-count: 2
    recommendations-out-0:
      producer:
        partition-key-expression: headers['partitionKey']
        partition-count: 2
    reviews-out-0:
      producer:
        partition-key-expression: headers['partitionKey']
        partition-count: 2

