server:
  port: 7002
  error.include-message: always

spring:
  application.name: recommendation
  data.mongodb:
      host: localhost
      port: 27017
      database: recommendationdb
  cloud:
    function.definition: messageProcessor
    stream:
      default.contentType: application/json
      bindings:
        messageProcessor-in-0:
          destination: recommendations
          group: recommendationsGroup
          consumer:
            max-attempts: 3
            back-off-initial-interval: 500
            back-off-max-interval: 1000
            back-off-multiplier: 2.0
      rabbit.bindings:
          messageProcessor-in-0:
            consumer:
              auto-bind-dlq: true
              republish-to-dlq: true
      kafka:
        bindings:
          messageProcessor-in-0:
            consumer:
              enable-dlq: true

logging:
  level:
    root: info
    org.tbl.microdaddy: debug
    org.springframework.data.mongodb.core.ReactiveMongoTemplate: debug




