server:
  port: 7003
  error.include-message: always

spring:
  application.name: review
  jpa:
    # usually set ddl-auto to none in production...
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://localhost/reviewdb
    hikari.initialization-fail-timeout: 60000
  cloud:
    function.definition: messageProcessor
    stream:
      default.contentType: application/json
      bindings:
        messageProcessor-in-0:
          destination: reviews
          group: reviewsGroup
          consumer:
            max-attempts: 3
            back-off-initial-interval: 500
            back-off-max-interval: 1000
            back-off-multiplier: 2.0
      rabbit.bindings:
        messageProcessor-in-0:
          consumer:
            auto-bind-dlq: true
            republish-to-dlq: true
      kafka:
        bindings:
          messageProcessor-in-0:
            consumer:
              enable-dlq: true


logging:
  level:
    root: info
    org.tbl.microdaddy: debug
    org.hibernate.sql: debug
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

---
spring:
  config.activate.on-profile: docker
  datasource.url: jdbc:mysql://mysql/reviewdb

server.port: 80

---
spring.config.activate.on-profile: production

spring:
  datasource.url: jdbc:mysql://172.17.0.1:3306/reviewdb


logging:
  level:
    root: WARN
    se.magnus: WARN
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN

---
spring:
  config.activate.on-profile: streaming_instance_0
  cloud.stream.bindings:
    messageProcessor-in-0.consumer.instance-index: 0

---
spring:
  config.activate.on-profile: streaming_instance_1
  cloud.stream.bindings:
    messageProcessor-in-0.consumer.instance-index: 1

---
spring:
  config.activate.on-profile: streaming_partitioned
  cloud.stream.bindings:
    messageProcessor-in-0:
      consumer:
        partitioned: true
        instance-count: 2
