spring.config.activate.on-profile: production

spring:
  datasource.url: jdbc:mysql://172.17.0.1:3306/reviewdb
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    root: WARN
    se.magnus: WARN
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
