fullnameOverride: mongodb

image:
  repository: registry.hub.docker.com/library
  name: mongodb
  tag: 6.0.6
  pullPolicy: IfNotPresent

ports:
  - containerPort: 27017

service:
  ports:
    - port: 27017
