apiVersion: v2
appVersion: "1.0"
description: Helm Chart for Spring Authorization Server
name: auth-server
version: 1.0.0

dependencies:
  - name: common
    version: 1.0.0
    repository: file://../../common



