spring:
  config:
    import: "optional:configserver:"
  application:
    name: product-composite
  cloud:
    config:
      fail-fast: true
      uri: http://localhost:8888
      username: username
      password: password
      retry:
        multiplier: 1.3
        max-attempts: 8
        max-interval: 5000
        initial-interval: 1000
  output:
    ansi:
      enabled: always


management:

# Note: This is the specific syntax required, and the host has to be updated.
#  zipkin.tracing.endpoint: http://zipkin:9411/api/v2/spans


logging:
  level:
    root: info
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"