ingress:
  host: minikube.me
  paths:
    - path: /oauth2
      service: auth-server
    - path: /login
      service: auth-server
    - path: /error
      service: auth-server
    - path: /product-composite
      service: product-composite
    - path: /actuator/health
      service: product-composite
    - path: /openapi
      service: product-composite
    - path: /webjars
      service: product-composite

secrets:

  rabbitmq-credentials:
    SPRING_RABBITMQ_USERNAME: rabbit-user-prod
    SPRING_RABBITMQ_PASSWORD: rabbit-pass-prod

#  rabbitmq-zipkin-credentials:
#    RABBIT_USER: rabbit-user-prod
#    RABBIT_PASS: rabbit-pass-prod
#
  mongodb-credentials:
    SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE: admin
    SPRING_DATA_MONGODB_USERNAME: mongodb-user-prod
    SPRING_DATA_MONGODB_PASSWORD: mongodb-pass-prod

  mysql-credentials:
    SPRING_DATASOURCE_USERNAME: mysql-user-prod
    SPRING_DATASOURCE_PASSWORD: mysql-pass-prod

auth-server:
  image:
    tag: v1
  env:
    SPRING_PROFILES_ACTIVE: "docker,production"
  envFromSecretRefs:
    - rabbitmq-credentials

product:
  image:
    tag: v1
  env:
    SPRING_PROFILES_ACTIVE: "docker,production"
  envFromSecretRefs:
    - rabbitmq-credentials
    - mongodb-credentials

recommendation:
  image:
    tag: v1
  env:
    SPRING_PROFILES_ACTIVE: "docker,production"
  envFromSecretRefs:
    - rabbitmq-credentials
    - mongodb-credentials

review:
  image:
    tag: v1
  env:
    SPRING_PROFILES_ACTIVE: "docker,production"
  envFromSecretRefs:
    - rabbitmq-credentials
    - mysql-credentials

product-composite:
  image:
    tag: v1
  env:
    SPRING_PROFILES_ACTIVE: "docker,production"
  envFromSecretRefs:
    - rabbitmq-credentials

zipkin-server:
  env:
    LOGGING_LEVEL_ROOT: WARN
#    RABBIT_ADDRESSES: 172.17.0.1
#  envFromSecretRefs:
#    - rabbitmq-zipkin-credentials
  resources:
    limits:
      memory: 600Mi
