server:
  port: 7002
  error:
    include-message: always

logging:
  level:
    root: info
    org.tbl.microdaddy: debug
---
spring:
  config:
    activate:
      on-profile: docker

server:
  port: 8080