fullnameOverride: mysql

image:
  repository: registry.hub.docker.com/library
  name: mysql
  tag: 8.0.33
  pullPolicy: IfNotPresent


ports:
  - containerPort: 3306

service:
  ports:
    - port: 3306
