fullnameOverride: mysql

annotations:
  sidecar.istio.io/inject: "false"

image:
  repository: registry.hub.docker.com/library
  name: mysql
  tag: 8.0.33
  pullPolicy: IfNotPresent

ports:
  - containerPort: 3306

service:
  ports:
    - name: mysql
      port: 3306
