server:
  port: 8888

spring:
  cloud:
    config:
      server:
        native:
          search-locations: file:${PWD}/config-repo
  security:
    user:
      name: username
      password: password

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    root: info
encrypt:
  key: my_encryption_key
---
spring:
  config:
    activate:
      on-profile: docker
  cloud:
    config:
      server:
        native:
          search-locations: file:/config-repo



